# Generated by Django 3.2.3 on 2021-07-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('telegono', models.IntegerField()),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
