# Generated by Django 3.2.3 on 2021-07-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_financiera', '0006_alter_cuenta_bancaria_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta_bancaria',
            name='saldo',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
